### ISSUE TITLE
PowerShell Error

### ISSUE THREAD

**Issue by toxi1701** [DataOne/YammerShell#2]
When i create a new community i get the following error message in PowerShell, also when i use the get-YmGroup command! 

The value for an Int32 was too large or too small.

Has anyone an idea?

**Comment by ghost** [comment]
Hi, this happens because the IDs are stored as `int` internally. But Yammer does not seem to use integers.
A fix would be to change the internal type to `string`

E.g. at this line: https://github.com/DataOne/YammerShell/blob/master/src/YammerShell/YammerObjects/YammerNetwork.cs#L7

**Comment by doadmin** [comment]
@toxi1701 Please try out [release 0.2](https://github.com/DataOne/YammerShell/releases/tag/v0.2). This should fix the problem!
